project:
  type: website

website:
  title: "Cerebral Mastication"
  image: img/logo.jpg
  site-url: https://cerebralmastication.com
  description: "Something to chew on..."
  repo-actions: edit
  open-graph:
    locale: es_ES
    site-name: "Cerebral Mastication"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CerebralMastication
      - icon: Mastodon
        href: https://mastodon.social/@Cmastication
      - icon: rss
        href: index.xml
        
format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true

editor: visual

